[project]
name = "homework-5"
version = "0.1.0"
description = "Homework 5 for the ML Zoomcamp course"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.0",
    "pandas>=2.3.3",
    "scikit-learn==1.6.1",
    "uvicorn>=0.38.0",
]
